contact:
  email: bizon@renci.org
  name: Chris Bizon
  x-id: https://github.com/cbizon
  x-role: responsible developer
description: 'ARAGORN: Performs a query operation which compiles data from numerous ARAGORN ranking agent services.'
servers:
- description: Default server
  url: https://aragorn.renci.org
#- description: localhost
#  url: http://127.0.0.1:5000
termsOfService: http://robokop.renci.org:7055/tos?service_long=ARAGORN&provider_long=RENCI
title: ARAGORN
version: 2.9.1
tags:
- name: translator
- name: ARA
- name: trapi
x-translator:
  biolink-version: 4.1.6
  component: ARA
  team:
  - Ranking Agent
  infores: infores:aragorn
x-trapi:
  version: 1.5.0
  operations:
  - lookup
  - enrich_results
  - overlay_connect_knodes
  - score
  - sort_results_score
  - filter_results_top_n
  - filter_kgraph_orphans
